import argparse
import ctypes

import torch
import torch.nn.functional as F
import torch_npu  # noqa: F401

from ptodsl.test_util import get_test_device


def torch_to_ctypes(tensor):
    return ctypes.c_void_p(tensor.data_ptr())


def load_lib(lib_path, block_dim=24):
    lib = ctypes.CDLL(lib_path)
    lib.call_kernel.argtypes = [
        ctypes.c_uint32,  # blockDim
        ctypes.c_void_p,  # stream
        ctypes.c_void_p,  # x
        ctypes.c_void_p,  # y (output)
        ctypes.c_uint32,  # batch
        ctypes.c_uint32,  # n_cols
    ]
    lib.call_kernel.restype = None

    def hardswish_func(x, y, batch, n_cols, block_dim=block_dim, stream_ptr=None):
        if stream_ptr is None:
            stream_ptr = torch.npu.current_stream()._as_parameter_
        lib.call_kernel(
            block_dim,
            stream_ptr,
            torch_to_ctypes(x),
            torch_to_ctypes(y),
            batch,
            n_cols,
        )

    return hardswish_func


def hardswish_ref(x):
    """Reference Hard-Swish: y = x * clamp(x + 3, 0, 6) / 6"""
    return F.hardswish(x.float()).to(x.dtype)


def test_hardswish(lib_path, block_dim=24):
    device = get_test_device()
    torch.npu.set_device(device)

    hardswish = load_lib(lib_path=lib_path, block_dim=block_dim)

    torch.manual_seed(0)
    dtype = torch.float16
    batch_list = [1, 4, 22, 65]
    n_cols_list = [128, 256, 512, 1024, 2048, 4096, 8192, 16384]

    results = []
    for batch in batch_list:
        for n_cols in n_cols_list:
            x = torch.randn(batch, n_cols, device=device, dtype=dtype).clamp(-8, 8)
            y = torch.empty(batch, n_cols, device=device, dtype=dtype)

            y_ref = hardswish_ref(x)
            hardswish(x, y, batch, n_cols)
            torch.npu.synchronize()

            is_match = True
            detail = ""
            try:
                torch.testing.assert_close(y, y_ref, rtol=1e-2, atol=1e-2)
            except AssertionError as err:
                is_match = False
                detail = str(err).strip() if str(err) else "assert_close failed"

            status = "match" if is_match else "mismatch"
            print(f"[{status}] batch={batch}, n_cols={n_cols}, lib={lib_path}")
            if detail:
                print("  detail:")
                print(detail)
            results.append((batch, n_cols, status, detail))

    print(f"\ndetailed summary for {lib_path}:")
    for batch, n_cols, status, detail in results:
        msg = f"  batch={batch}, n_cols={n_cols}, status={status}"
        print(msg)
        if detail:
            print("    detail:")
            print(detail)
    return results


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--lib",
        default="./hardswish_lib.so",
        help="Path to the shared library generated by compile.sh.",
    )
    parser.add_argument(
        "--block-dim",
        type=int,
        default=24,
        help="Kernel blockDim (default: 24).",
    )
    args = parser.parse_args()
    test_hardswish(args.lib, block_dim=args.block_dim)
