"""Generate caller.cpp for a given TopK kernel function name.

The generated file wraps the NPU kernel launch in an ``extern "C"`` function
that can be called from Python via ctypes.

n_rows and blockDim are passed at call time so the same shared library
handles any row count and block dimension without recompilation.

Usage
-----
  python caller.py topk_c512_k256
"""

import argparse


def generate(fn: str) -> str:
    return f"""\
// Auto-generated by caller.py – do not edit by hand.
#include "{fn}.cpp"

extern "C" void call_{fn}(
    uint32_t  blockDim,
    void     *stream,
    uint8_t  *src,
    uint8_t  *inIdx,
    uint8_t  *out_scores,
    uint8_t  *out_indices,
    int32_t   n_rows)
{{
    {fn}<<<blockDim, nullptr, stream>>>(
        reinterpret_cast<float    *>(src),
        reinterpret_cast<uint32_t *>(inIdx),
        reinterpret_cast<float    *>(out_scores),
        reinterpret_cast<uint32_t *>(out_indices),
        n_rows);
}}
"""


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("fn_name", help="e.g. topk_c512_k256")
    args = parser.parse_args()
    print(generate(args.fn_name), end="")
