import argparse
import ctypes
import math

import torch
import torch_npu  # noqa: F401

from ptodsl.test_util import get_test_device


def torch_to_ctypes(tensor):
    return ctypes.c_void_p(tensor.data_ptr())


def load_lib(lib_path, block_dim=24):
    lib = ctypes.CDLL(lib_path)
    lib.call_kernel.argtypes = [
        ctypes.c_uint32,  # blockDim
        ctypes.c_void_p,  # stream
        ctypes.c_void_p,  # x (in-place)
        ctypes.c_uint32,  # batch
        ctypes.c_uint32,  # n
        ctypes.c_uint32,  # log2_n
    ]
    lib.call_kernel.restype = None

    def hadamard_func(x, batch, n, log2_n, block_dim=block_dim, stream_ptr=None):
        if stream_ptr is None:
            stream_ptr = torch.npu.current_stream()._as_parameter_
        lib.call_kernel(
            block_dim,
            stream_ptr,
            torch_to_ctypes(x),
            batch,
            n,
            log2_n,
        )

    return hadamard_func


def hadamard_ref_inplace(x):
    """Reference FHT matching TGATHER(P0101/P1010) + TADD/TSUB layout."""
    x = x.clone()
    n = x.shape[-1]
    n_half = n // 2
    log2_n = int(math.log2(n))
    for _ in range(log2_n):
        even = x[..., 0::2].clone()
        odd = x[..., 1::2].clone()
        x[..., :n_half] = even + odd
        x[..., n_half:] = even - odd
    return x


def _is_power_of_two(v):
    return v > 0 and (v & (v - 1)) == 0


def test_hadamard(lib_path, block_dim=24):
    device = get_test_device()
    torch.npu.set_device(device)

    hadamard = load_lib(lib_path=lib_path, block_dim=block_dim)

    torch.manual_seed(0)
    dtype = torch.float16
    batch_list = [1, 7, 29, 65]
    n_list = [128, 256, 512, 1024, 2048, 4096, 8192, 16384]

    results = []
    for batch in batch_list:
        for n in n_list:
            if not _is_power_of_two(n):
                continue
            log2_n = int(math.log2(n))
            x = torch.randn(batch, n, device=device, dtype=dtype)
            y_ref = hadamard_ref_inplace(x)

            hadamard(x, batch, n, log2_n)
            torch.npu.synchronize()

            is_match = True
            detail = ""
            try:
                torch.testing.assert_close(x, y_ref)
            except AssertionError as err:
                is_match = False
                detail = str(err).strip() if str(err) else "assert_close failed"

            status = "match" if is_match else "mismatch"
            print(f"[{status}] batch={batch}, n={n}, lib={lib_path}")
            if detail:
                print("  detail:")
                print(detail)
            results.append((batch, n, status, detail))

    print(f"detailed summary for {lib_path}:")
    for batch, n, status, detail in results:
        msg = f"  batch={batch}, n={n}, status={status}"
        print(msg)
        if detail:
            print("    detail:")
            print(detail)
    return results


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--lib",
        default="./hadamard_manual_sync_lib.so",
        help="Path to the shared library generated by compile.sh.",
    )
    parser.add_argument(
        "--block-dim",
        type=int,
        default=24,
        help="Kernel blockDim (default: 24).",
    )
    parser.add_argument(
        "--test-both",
        action="store_true",
        help="Test both auto-sync and manual-sync libraries.",
    )
    args = parser.parse_args()

    if args.test_both:
        test_hadamard("./hadamard_auto_sync_lib.so", block_dim=args.block_dim)
        test_hadamard("./hadamard_manual_sync_lib.so", block_dim=args.block_dim)
    else:
        test_hadamard(args.lib, block_dim=args.block_dim)
