#pragma once
// Auto-generated by scripts/generate_cases.py. Do not edit manually.
// clang-format off
#include <cstddef>

#define TFA_FOR_EACH_CASE(MACRO) \
    MACRO(3072, 128, 1024, 128, 128, 256, 4, false) \
    MACRO(3072, 128, 1024, 128, 128, 512, 4, false) \
    MACRO(3072, 128, 1024, 128, 128, 1024, 4, false) \
    MACRO(3072, 128, 2048, 128, 128, 256, 4, false) \
    MACRO(3072, 128, 2048, 128, 128, 512, 4, false) \
    MACRO(3072, 128, 2048, 128, 128, 1024, 4, false) \
    MACRO(3072, 128, 4096, 128, 128, 256, 4, false) \
    MACRO(3072, 128, 4096, 128, 128, 512, 4, false) \
    MACRO(3072, 128, 4096, 128, 128, 1024, 4, false) \
    MACRO(3072, 128, 8192, 128, 128, 256, 4, false) \
    MACRO(3072, 128, 8192, 128, 128, 512, 4, false) \
    MACRO(3072, 128, 8192, 128, 128, 1024, 4, false) \
    MACRO(3072, 128, 16384, 128, 128, 256, 4, false) \
    MACRO(3072, 128, 16384, 128, 128, 512, 4, false) \
    MACRO(3072, 128, 16384, 128, 128, 1024, 4, false) \
    MACRO(3072, 128, 32768, 128, 128, 256, 4, false) \
    MACRO(3072, 128, 32768, 128, 128, 512, 4, false) \
    MACRO(3072, 128, 32768, 128, 128, 1024, 4, false) \
    MACRO(3072, 128, 65536, 128, 128, 256, 4, false) \
    MACRO(3072, 128, 65536, 128, 128, 512, 4, false) \
    MACRO(3072, 128, 65536, 128, 128, 1024, 4, false) \
    MACRO(3072, 128, 131072, 128, 128, 256, 4, false) \
    MACRO(3072, 128, 131072, 128, 128, 512, 4, false) \
    MACRO(3072, 128, 131072, 128, 128, 1024, 4, false)

struct GeneratedTfaCase {
    int s0;
    int head_size;
    int s1;
    int cube_s0;
    int cube_s1;
    int tile_s1;
    int qk_preload;
    bool causal_mask;
    const char *name;
};

static constexpr GeneratedTfaCase kGeneratedTfaCases[] = {
    {3072, 128, 1024, 128, 128, 256, 4, false, "case_float_H_128_S0_3072_S1_1024"},
    {3072, 128, 1024, 128, 128, 512, 4, false, "case_float_H_128_S0_3072_S1_1024"},
    {3072, 128, 1024, 128, 128, 1024, 4, false, "case_float_H_128_S0_3072_S1_1024"},
    {3072, 128, 2048, 128, 128, 256, 4, false, "case_float_H_128_S0_3072_S1_2048"},
    {3072, 128, 2048, 128, 128, 512, 4, false, "case_float_H_128_S0_3072_S1_2048"},
    {3072, 128, 2048, 128, 128, 1024, 4, false, "case_float_H_128_S0_3072_S1_2048"},
    {3072, 128, 4096, 128, 128, 256, 4, false, "case_float_H_128_S0_3072_S1_4096"},
    {3072, 128, 4096, 128, 128, 512, 4, false, "case_float_H_128_S0_3072_S1_4096"},
    {3072, 128, 4096, 128, 128, 1024, 4, false, "case_float_H_128_S0_3072_S1_4096"},
    {3072, 128, 8192, 128, 128, 256, 4, false, "case_float_H_128_S0_3072_S1_8192"},
    {3072, 128, 8192, 128, 128, 512, 4, false, "case_float_H_128_S0_3072_S1_8192"},
    {3072, 128, 8192, 128, 128, 1024, 4, false, "case_float_H_128_S0_3072_S1_8192"},
    {3072, 128, 16384, 128, 128, 256, 4, false, "case_float_H_128_S0_3072_S1_16384"},
    {3072, 128, 16384, 128, 128, 512, 4, false, "case_float_H_128_S0_3072_S1_16384"},
    {3072, 128, 16384, 128, 128, 1024, 4, false, "case_float_H_128_S0_3072_S1_16384"},
    {3072, 128, 32768, 128, 128, 256, 4, false, "case_float_H_128_S0_3072_S1_32768"},
    {3072, 128, 32768, 128, 128, 512, 4, false, "case_float_H_128_S0_3072_S1_32768"},
    {3072, 128, 32768, 128, 128, 1024, 4, false, "case_float_H_128_S0_3072_S1_32768"},
    {3072, 128, 65536, 128, 128, 256, 4, false, "case_float_H_128_S0_3072_S1_65536"},
    {3072, 128, 65536, 128, 128, 512, 4, false, "case_float_H_128_S0_3072_S1_65536"},
    {3072, 128, 65536, 128, 128, 1024, 4, false, "case_float_H_128_S0_3072_S1_65536"},
    {3072, 128, 131072, 128, 128, 256, 4, false, "case_float_H_128_S0_3072_S1_131072"},
    {3072, 128, 131072, 128, 128, 512, 4, false, "case_float_H_128_S0_3072_S1_131072"},
    {3072, 128, 131072, 128, 128, 1024, 4, false, "case_float_H_128_S0_3072_S1_131072"}
};
static constexpr std::size_t kGeneratedTfaCasesCount = sizeof(kGeneratedTfaCases) / sizeof(kGeneratedTfaCases[0]);
// clang-format on
